server:
  port: 8081

spring:
#  配置数据源
  datasource:
    username: sa
    password: 12345678
    url: jdbc:sqlserver://127.0.0.1:1433;Database=picture_depot_2
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
#  配置redis
  redis:
    host: 8.141.151.176
    password: haihaihai
# 文件上传大小限制
  servlet:
    multipart:
      enabled: true               #是否启用http上传处理
      max-request-size: 100MB     #最大请求文件的大小
      max-file-size: 20MB         #设置单个文件最大长度
      file-size-threshold: 20MB   #当文件达到多少时进行磁盘写入

mybatis:
  mapperLocations:
    - classpath:mapper/**.xml
  typeAliasesPackage: com.qiao.picturedepot.pojo.domain
  configuration:
    mapUnderscoreToCamelCase: true

#pagehelper
pagehelper:
  helperDialect: sqlserver
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

# 日志
#logging:
#  file:
#    name: application.log
#  # 日志级别
#  level:
#    root: INFO
#    com.qiao.picturedepot: INFO